.TH twitch-cli 1 twitch-cli
.SH NAME 
twitch-cli is a lightweight cli to watch and manage twitch streamer.
.SH SYNOPSIS
.B twitch-cli
.SH HOW TO USE
.B twitch-cli
.PP
First, navigate to ~/.config/twitch-cli/streamers.txt.
On this file, you can add streamers that you want to follow, navigate to https://www.twitch.tv and find your streamer. 
The real name is in the url, but most of the time, it's the one you're thinking about. Be careful to only add one name per line and not to leave empty lines at the start or end.
.PP
Then, simply run 
.B twitch-cli 
to get a list of you streamer activity. Select the one you want to watch and mpv will start. 
.SH CONFIGURATION
.TP
.B config file location
The configuration file is located at ~/.config/twitch-cli/streamers.txt
.SH MORE INFORMATION
Twitch-cli has two dependencies: cURL to fetch streamer status info and mpv to play the stream.
.SH AUTHORS
Written by Paul Chambaz <paul.chambazz@gmail.com> in 2021.
.SH LICENSE
GPLv2
.SH SEE ALSO
.BR curl (1),
.BR mpv (1)
