.TH twitch-cli 1 twitch-cli
.SH NAME 
twitch-cli is a lightweight cli to watch and manage twitch streamer.
.SH SYNOPSIS
.B twitch-cli
.SH HOW TO USE
.B twitch-cli
.PP
To add streamers to the program, you need to edit the config.h file located in the include folder.
Here is an example
.PP
char *streamers[] = {
  "streamer1",
  "streamer2",
  "streamer3"
};
.PP
To get the correct name go to https://www.twitch.tv and go to a streamer url.
The correct name is in the url.
.PP
Then, simply run 
.B twitch-cli 
to get a list of you streamer activity. Select the one you want to watch and mpv will start. 
.PP
If you want to add more streamers, simply modify the config.h again and reinstall.
.SH MORE INFORMATION
Twitch-cli has three dependencies: cURL to fetch streamer status info, mpv to play the stream and yt-dlp for mpv to get thre stream.
.SH AUTHORS
Written by Paul Chambaz <paul.chambazz@gmail.com> in 2021.
.SH LICENSE
GPLv2
.SH SEE ALSO
.BR curl (1),
.BR mpv (1),
.BR yt-dlp (1)
